openapi: 3.0.0

info:
  description: "twitter-client-severについてのAPI"
  version: "1.0.0"
  title: "twitter-client-server API"
  termsOfService: "http://swagger.io/terms/"
paths:
  /tweet/{tweetID}/stamps/{stampID}:
    post:
      tags:
        - stamp
      description: 指定したメッセージに指定したスタンプを押します。
      parameters:
        - in: path
          name: tweetID
          schema:
            type: integer
          description: 操作の対象となるツイートのID
        - in: path
          name: stampID
          schema:
            type: string
          description: 操作の対象となるスタンプのID
  /tweet/{tweetID}/stamps:
    get:
      tags:
        - stamp
      description: 指定したツイートに押されているスタンプを全て取得します。
      parameters:
        - in: path
          name: tweetID
          schema:
            type: integer
          description: 操作の対象となるツイートのID
  /tweet/{tweetID}/stamps/{stampID}/destroy:
    post:
      tags:
        - stamp
      description: 指定したツイートに押されている指定したスタンプを外します。
  /tweet/new:
    post:
      tags:
        - tweet
      description: ツイートを投稿します。
  /tweet/{tweetID}/retweet:
    post:
      tags:
        - tweet
      description: 指定したツイートをリツイートします。
  /tweet/{tweetID}/unretweet:
    post:
      tags:
        - tweet
      description: 指定したツイートのリツイートを取り消します。
  /tweet/{tweetID}/favorites:
    post:
      tags:
        - tweet
      description: 指定したツイートにいいね（お気に入り）をつけます。
  /tweet/{tweetID}/favorites/destroy:
    post:
      tags:
        - tweet
      description: 指定したツイートのいいね（お気に入り）を外します。
  /statuses/home_timeline:
    get:
      tags:
        - timeline
      description: ホームのタイムラインを取得します。
  /lists/list:
    get:
      tags:
        - timeline
      description: ユーザーのリスト一覧を返します。
  /lists/{listID}/statuses:
    get:
      tags:
       - timeline
      description: リストのタイムラインを取得します。
      parameters:
        - in: path
          name: listID
          schema:
            type: integer
          description: タイムラインを取得するリストのID

components:
  schemas:
    Tweet:
      description:
        anacondaのTweet構造体
        ここには主要なものしか書いてません
      type: object
      properties:
        id:
          type: int64
          description: ツイートのID
        text:
          type: string
          description: ツイートの内容
        user:
          $ref: "#/components/schemas/User"
        created_at:
          type: string
          description: ツイートした日時
        favorited_count:
          type: int
          description: ツイートへのいいねの数
        favorited:
          type: bool
          description: ユーザーがいいねをつけているか否か
        retweet_count:
          type: int
          description: ツイートへのリツイートの数
        retweeted:
          type: bool
          description: ユーザーがリツイートしているか否か
        in_reply_to_screen_name:
          type: string
          description: このツイートがリプライである場合、リプライ相手のscreen_name
        in_reply_to_user_id:
          type: int64
          description: このツイートがリプライである場合、リプライ相手のid
        in_reply_to_status_id:
          type: int64
          description: このツイートがリプライである場合、リプライ先のツイートのid
        entities:
          $ref: "#/components/schemas/Entities"
        
    User:
      description: 
        anacondaのUser構造体
        ここには主要なものしか書いていません
      type: object
      properties:
        id:
          type: int64
          description: ユーザーのid
        name:
          type: string
          description: ユーザーの名前
        screen_name:
          type: string
          description: ユーザー名(@...)
        default_profile:
          type: bool
          description: プロフィールが初期設定のままであるか否か
        default_profile_image:
          type: bool
          description: プロフィール画像が初期設定のままであるか否か
        profile_image_url_https:
          type: string
          description: ユーザー画像のURL
        profile_banner_url:
          type: string
          description: バーナー画像のURL
        description:
          type: string
          description: プロフィールの説明欄のテキスト
        statuses_count:
          type: int
          description: ツイートの数
        favourites_count:
          type: int
          description: いいねの数
        followers_count:
          type: int
          description: フォロワーの数
        friends_count:
          type: int
          description: フレンド(フォロイー)の数
        following:
          type: bool
          description: このユーザーをフォローしているか
        follow_request_sent:
          type: bool
          description: このユーザーにフォローリクエストを出しているか否か
        protected:
          type: bool
          description: アカウントに鍵を掛けているか否か
        location:
          type: string
          description: 所在地
    
    Entities:
      description: 
        ツイートに付随する情報
        anacondaのEntities構造体
      type: object
      properties:
        hashtags:
          type: array
          description: ハッシュタグの情報
          items:
            type: object
            properties:
              text:
                type: string
                description: ハッシュタグのテキスト
              indices:
                type: array
                description: ハッシュタグの開始位置・終了位置を指定
                items:
                  type: int
        urls:
          type: array
          description: URLの情報
          items:
            type: object
            properties:
              url:
                type: string
              expanded_url:
                type: string
              display_url:
                type: string
              indices:
                type: array
                items:
                  type: int
        user_mentions:
          type: array
          items:
            type: object
            properties:
              name: 
                type: string
              screen_name:
                type: string
              id:
                type: int64
              indices:
                type: array
                items:
                  type: int
        media:
          type: array
          items:
            type: object
            properties:
              id:
                type: int64
              media_url:
                type: string
              url:
                type: string
              expanded_url:
                type: string
              display_url:
                type: string
              size:
                type: MediaSizes
    Stamp:
      description: ツイートに押されたスタンプの情報
      type: object
      properties:
        stamp_id:
          type: string
          description: twemojiの絵文字のid
        tweet_id:
          type: int64
          description: ツイートのid
        user_id:
          type: int64
          description: スタンプを押した人のユーザーid
        user_screen_name:
          type: string
          description: スタンプを押した人のユーザー名(@...)
        count:
          type: int
          description: 押されたスタンプの数
        created_at:
          type: string
          description: 最初に押した日時
        updated_at:
          type: string
          description: 最後に押した日時
        
              